[features]
seeds = false
[programs.devnet]
mint_nft = "ApoJnWfacBg3dy84FS8QUt9SE9xyzFaV7x33vcCKPTkd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abdullahqureshi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
